### ISSUE TITLE
Question about checksum

### ISSUE THREAD

**Issue by teebu** [ripper2hl/curp#27]
I'm trying to understand CURP. The first result when I search for CURP validator I get this page:

https://support.sas.com/documentation/onlinedoc/qkb/27/QKBCI27/Help/Content/QKBCI_ESMEX/QKBCI_ESMEX_ID_CURP-Validation.html

Their two 'valid' examples provided both come up as invalid in the results when running this package.
 
Is their documentation wrong?

```
ZAZD801124MBSYQN13
RUNO390705HSLPTC02
```

I also tried another package, also showing those two are invalid.

**Comment by ripper2hl** [comment]
You should read the official documentation.
But the numbers are invalid.
Example :  

CURP:ZAZD801124MBSYQN13
born date: 80/11/24 80th november 1924

CURP: RUNO390705HSLPTC02
born date: 390705 39th june 1905

**Comment by teebu** [comment]
Thanks for the response, I wasn't sure what was happening. I wonder why they gave invalid examples. 

I should mention the regex validation might need an 'X' for non binary gender.

A one-letter gender indicator (H for male (hombre in Spanish), M for female (mujer in Spanish), or X for non-binary); [[1]](https://en.wikipedia.org/wiki/Unique_Population_Registry_Code#cite_note-1)

**Comment by ripper2hl** [comment]
> Thanks for the response, I wasn't sure what was happening. I wonder why they gave invalid examples.
> 
> I should mention the regex validation might need an 'X' for non binary gender.
> 
> A one-letter gender indicator (H for male (hombre in Spanish), M for female (mujer in Spanish), or X for non-binary); [[1]](https://en.wikipedia.org/wiki/Unique_Population_Registry_Code#cite_note-1)

yep the X is for non-binary persons, but now we don't have some real examples or official examples to generate or create that unit test.

You can watch #24
